"""criação da tabela comentario

Revision ID: 18e1e702204c
Revises: 
Create Date: 2025-05-08 10:35:37.134935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e1e702204c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=200), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('critica_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['critica_id'], ['critica.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    # ### end Alembic commands ###
